"""empty message

Revision ID: b744f793eb9e
Revises: 7793ed670d07
Create Date: 2022-03-08 14:26:19.368742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b744f793eb9e'
down_revision = '7793ed670d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('shot', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('created', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated', mysql.TIMESTAMP(), nullable=True),
    sa.Column('comment', sa.Text(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('shot')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
